[package]
name = "fmodeparser"
version = "0.1.0"
edition = "2021"
license = "GPL-3"
authors = ["allawiii <alighraibeh87@gmail.com>"]
description = "A tool to parse the file permission into a unix-like text representation"
[dependencies]
regex = "1.10.6"
